const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lines=s=>esc(s).replace(/\n/g,'<br>');
const label=(n,s)=>`<div class="eyebrow"><span>${n}</span>${s}</div>`;
const list=a=>`<ul>${a.map(s=>`<li>${esc(s)}</li>`).join('')}</ul>`;
async function init(){const response=await fetch('content.json');if(!response.ok)throw Error('Content unavailable');const d=await response.json();
document.querySelector('#main').innerHTML=`
<section id="home" class="hero"><div class="hero-shade"></div><div class="hero-content"><p class="hero-eyebrow">${esc(d.hero.eyebrow)}</p><h1>${esc(d.hero.title)}<br><em>${esc(d.hero.accent)}</em></h1><p class="hero-description">${esc(d.hero.description)}</p><div class="actions"><a class="button" href="#how-it-works">See how it works <span>↓</span></a><a class="button outline" href="#get-involved">Get involved <span>↗</span></a></div></div><div class="hero-bottom"><span>SUSTAINABILITY COLLABORATION CENTER</span><p>${esc(d.hero.caption)}</p><a href="#problem" aria-label="Scroll to the problem">↓</a></div></section>
<div class="pilot-strip"><div><span class="mini">OUR STARTING POINT</span><strong>A focused beginning.<br>A shared ambition.</strong></div><div><span class="mini">WHERE</span><strong>Suisse romande</strong></div><div><span class="mini">WHAT</span><strong>Climate adaptation</strong></div><div><span class="sdg-number">13</span><div><span class="mini">SUSTAINABLE DEVELOPMENT GOAL</span><strong>Climate action</strong></div></div></div>
<section id="problem" class="section light">${label('01','THE DISCONNECT')}<div class="section-heading"><h2>${esc(d.problem.title)}</h2><p>${esc(d.problem.intro)}</p></div><div class="three-cards">${d.problem.cards.map((c,i)=>`<article><span class="card-num">0${i+1}</span><h3>${esc(c[0])}</h3><p>${esc(c[1])}</p></article>`).join('')}</div><p class="closing">${esc(d.problem.closing)}</p></section>
<section id="idea" class="section dark">${label('02','A DIFFERENT STARTING POINT')}<div class="idea-grid"><div><h2>${lines(d.idea.title)}</h2><p class="lead">${esc(d.idea.intro)}</p><p class="muted">${esc(d.idea.body)}</p><div class="need-connection"><span>Real needs</span><span aria-hidden="true">↔</span><span>Relevant knowledge</span></div></div><div class="comparison"><div class="comparison-head"><span>A typical registry</span><strong>Need & Know</strong></div>${d.idea.rows.map(r=>`<div><span>${esc(r[0])}</span><strong>${esc(r[1])}</strong></div>`).join('')}</div></div></section>
<section id="how-it-works" class="section light"><div class="how-heading"><div>${label('03','HOW IT WORKS')}<h2>From a problem to a conversation,<br>in five steps.</h2></div><figure class="platform-preview"><img src="assets/platform-ui.png" alt="Early Need & Know application concept showing a dashboard with projects, challenges and activity" width="1672" height="941" loading="lazy"><figcaption>Early design concept · Illustrative data</figcaption></figure></div><div class="steps">${d.steps.map((s,i)=>`<article class="step ${i===3?'human':''}"><span class="step-num">0${i+1}</span>${i===3?'<span class="human-label">THE HUMAN PART</span>':''}<h3>${esc(s[0])}</h3><p>${esc(s[1])}</p></article>`).join('')}</div><p class="closing">Search can be automated. Building trust between two people who’ve never met can’t.<br><strong>That’s why there’s always a human in step four.</strong></p></section>
<section id="for-you" class="section soft">${label('04','FIND YOUR PLACE')}<div class="section-heading"><h2>What each side gives.<br>What each side gets.</h2><p>A collaboration only works if it’s worth it for everyone. Here’s the honest version for each group.</p></div><div class="audiences">${d.audiences.map((a,i)=>`<details id="${a.id}" ${i===0?'open':''}><summary><span class="audience-num">0${i+1}</span><h3>${esc(a.label)}</h3>${a.later?'<span class="phase-tag">Later phase</span>':''}<span class="plus" aria-hidden="true">+</span></summary><div class="audience-body"><h4>${esc(a.headline)}</h4><div class="give-get"><div><span class="mini">WHAT YOU GET</span>${list(a.get)}</div><div><span class="mini">WHAT WE ASK</span>${list(a.ask)}${a.note?`<p class="note">${esc(a.note)}</p>`:''}<a class="text-link" href="#get-involved">Let’s talk <span>↗</span></a></div></div></div></details>`).join('')}</div></section>
<section id="platform" class="section dark">${label('05','INSIDE THE PLATFORM')}<div class="section-heading"><h2>Built around the need,<br>not the profile.</h2><p>The platform we’re building makes the reasoning visible and keeps the people involved in control.</p></div><div class="platform-grid"><div class="features">${d.features.map((f,i)=>`<article><span class="feature-number">0${i+1}</span><div><h3>${esc(f[0])}</h3><p>${esc(f[1])}</p></div></article>`).join('')}</div><div class="mock-wrap"><div class="mock-caption">A CONNECTION IN PRACTICE <span>Illustrative example</span></div><article class="need-record"><div class="record-top"><span>THE NEED</span><span class="record-tag">Climate adaptation</span></div><h3>How can we keep our neighbourhood cool?</h3><p>“We need practical ways to reduce summer heat in public spaces, with limited water and a small budget.”</p><div class="record-meta"><span>Location <b>Suisse romande</b></span><span>Help needed <b>Evidence & methods</b></span></div></article><div class="match-connector">↓ <span>Relevant knowledge, with a reason</span></div><article class="match-card"><span class="mini">SUGGESTED CONNECTION</span><h3>Research on urban cooling through nature-based solutions</h3><dl><dt>Why it could help</dt><dd>Looks at planting and shade strategies for neighbourhood-scale heat, including water constraints.</dd><dt>What we don’t know yet</dt><dd>Whether the findings apply to this site, and whether the research team is available.</dd></dl><div class="broker-stamp">Human review before any introduction</div></article><p class="mock-footnote">Example only. No match or partnership is being claimed.</p></div></div></section>
<section id="ai" class="section light">${label('06','AI, WITH BOUNDARIES')}<h2>AI helps us find connections.<br>People decide what they mean.</h2><div class="ai-grid"><article><h3>What AI does</h3>${list(d.ai.does)}</article><article><h3>What AI never does</h3>${list(d.ai.never)}</article></div><div class="ai-rule"><span>EVERY SUGGESTION SHOWS</span><p>The suggestion. The reason. What we don’t know.<br><strong>And your control to edit or reject it.</strong></p></div></section>
<section id="starting" class="section pilot">${label('07','WHERE WE’RE STARTING')}<div class="section-heading"><h2>Deep before wide.</h2><p>${esc(d.pilot.intro)}</p></div><div class="facts">${d.pilot.facts.map((f,i)=>`<div><div class="fact-top"><strong>${f[0]}</strong><img class="fact-icon ${i===0?'fact-icon-map':''}" src="assets/${['pilot-switzerland.svg','pilot-climate-action.svg','pilot-conversations.svg','pilot-project.svg'][i]}" alt="${i===1?'SDG 13: Climate Action':''}" width="${[910,94,94,98][i]}" height="${[584,94,94,87][i]}" loading="lazy"></div><h3>${esc(f[1])}</h3><p>${esc(f[2])}</p></div>`).join('')}</div><div class="roadmap">${d.pilot.phases.map((p,i)=>`<article><span>PHASE 0${i+1}</span><h3>${esc(p[0])}</h3><p>${esc(p[1])}</p></article>`).join('')}</div><p class="roadmap-note">Planned sequence. Progress depends on partner conversations, association registration and funding.</p><aside id="sdg-alignment" class="sdg-alignment" aria-labelledby="sdg-heading"><img src="assets/un-sdg-logo.svg" alt="Sustainable Development Goals" width="1502" height="170" loading="lazy"><div><h3 id="sdg-heading">${esc(d.pilot.sdg.title)}</h3><p>${esc(d.pilot.sdg.body)}</p></div></aside></section>
<section id="scc" class="section light">${label('08','THE PEOPLE BEHIND IT')}<div class="scc-identity"><img class="scc-logo" src="assets/scc-logo.svg" alt="SCC — Sustainability Collaboration Center" width="1069" height="269" loading="lazy"><div><h2>${lines(d.scc.title)}</h2><div class="scc-description"><p>${esc(d.scc.intro)}</p><p>${esc(d.scc.body)}</p></div></div></div><div class="values">${d.scc.values.map(v=>`<article><h3>${esc(v[0])}</h3><p>${esc(v[1])}</p></article>`).join('')}</div><div class="founders">${d.scc.founders.map(f=>`<article><img class="founder-photo" src="assets/${f[0]==='RM'?'radhika-profile.png':'nikos-profile.png'}" alt="${esc(f[1])}" width="1254" height="1254" loading="lazy"><div><h3>${esc(f[1])}</h3><span class="founder-role">${esc(f[2])}</span><p>${esc(f[3])}</p></div></article>`).join('')}</div><p class="closing">One of us brings the network and the field. The other brings the product and the technology.<br><strong>Need & Know needs both.</strong></p></section>
<section id="get-involved" class="section contact">${label('09','GET INVOLVED')}<div class="section-heading"><h2>${lines(d.contact.title)}</h2><p>${esc(d.contact.intro)}</p></div><div class="contact-grid">${d.contact.asks.map(a=>`<article><h3>${esc(a[0])}</h3><p>${esc(a[1])}</p><a href="mailto:${esc(d.brand.email)}?subject=${encodeURIComponent(a[3])}">${esc(a[2])} <span>↗</span></a></article>`).join('')}</div><div class="direct-contact"><span>Start a conversation with Nikos</span><a href="mailto:${esc(d.brand.email)}">${esc(d.brand.email)} ↗</a></div></section>`;
document.querySelector('footer').innerHTML=`<div class="footer-top"><a class="brand" href="#home"><img class="brand-logo" src="assets/need-and-know-logo-white.svg" alt="Need & Know — People, Ideas, Impact" width="1233" height="233" loading="lazy"></a><p>An initiative of the Sustainability Collaboration Center (SCC), Switzerland.<br>This site describes a platform in development. Examples are illustrative.</p><a href="#home" aria-label="Back to top">↑</a></div><div class="footer-bottom"><span>© 2026 Sustainability Collaboration Center</span><span>Knowledge shared. Progress together.</span></div>`;
function revealHash(){const el=document.getElementById(decodeURIComponent(location.hash.slice(1)));if(el){if(el.tagName==='DETAILS')el.open=true;requestAnimationFrame(()=>el.scrollIntoView({behavior:'instant',block:'start'}));}}window.addEventListener('hashchange',revealHash);if(location.hash)revealHash();
const menu=document.querySelector('.menu'),nav=document.querySelector('nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',open);nav.classList.toggle('open',open);});nav.addEventListener('click',e=>{if(e.target.closest('a')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}});
}
init().catch(()=>{document.querySelector('#main').innerHTML='<section class="section light"><h1>Need & Know</h1><p>We couldn’t load the page. Please refresh, or <a href="mailto:wedoux@gmail.com">contact Nikos</a>.</p></section>';});
